#! /bin/sh

gap=8
XFPANEL_HEIGHT=0
POLYBAR_HEIGHT=32
export gap
export XFPANEL_HEIGHT
export POLYBAR_HEIGHT

bspc monitor -d 1 2 3 4 5 6

# Autostart
sxhkd &
/usr/lib64/polkit-gnome/polkit-gnome-authentication-agent-1 &
compton -b &
nitrogen --restore &
/home/ms/code/bash/launch_poly.sh
# xfce4-panel -d &
xfce4-power-manager &
tlp start
xfsettingsd
libinput-gestures-setup start
# wal -R -n

# Gaps
bspc config window_gap      $gap;
bspc config top_padding     $(($XFPANEL_HEIGHT + $gap))
bspc config left_padding    $gap
bspc config right_padding   $gap
bspc config bottom_padding  $(($POLYBAR_HEIGHT + 2 * $gap))

# Misc
bspc config split_ratio             0.50
bspc config focus_follows_pointer   true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Borders
bspc config border_width            6
# bspc config focused_border_color    "#262422"
# bspc config normal_border_color     "#66a3cc"
# bspc config presel_feedback_color   "#262422"
# bspc config focused_border_color    "#e8a097"
bspc config focused_border_color    "#e8a097"
bspc config normal_border_color     "#2f343f"
bspc config presel_feedback_color   "#e8a097"

# # wal
# # source the colors.
# . "${HOME}/.cache/wal/colors.sh"

# # Set the border colors.
# bspc config normal_border_color "$color1"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color15"
# bspc config presel_border_color "$color1"

# Rules
bspc rule -a peek 				        state=floating
bspc rule -a Orage 				        state=floating
bspc rule -a Galculator 		        state=floating
bspc rule -a "*:xfce4-appfinder"        state=floating
bspc rule -a "*:nitrogen" 		        state=floating
bspc rule -a "*:virtualbox"		        state=floating
bspc rule -a "*:pulseeffects" 	        desktop=5 state=floating follow=on
bspc rule -a "*:messengerfordesktop" 	desktop=4 follow=on
bspc rule -a "*:spotify"                desktop=6 follow=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Google Chrome desktop='^2'

# -------
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
