#! /bin/sh

gap=8
XFPANEL_HEIGHT=27
POLYBAR_HEIGHT=32
export gap
export XFPANEL_HEIGHT
export POLYBAR_HEIGHT

bspc monitor -d I II III IV V VI VII VIII IX X

# Autostart
sxhkd &
# source /home/ms/.config/bspwm/autostart
compton -b &
nitrogen --restore &
/home/ms/code/shell_scripts/launch_poly.sh
xfce4-panel -d &
xfce4-power-manager &
tlp start
xfsettingsd
libinput-gestures-setup start
wal -R -n -t

# Gaps
bspc config window_gap      $gap;
bspc config top_padding     $(($XFPANEL_HEIGHT + $gap))
bspc config left_padding    $gap
bspc config right_padding   $gap
bspc config bottom_padding  $(($POLYBAR_HEIGHT + 2 * $gap))

# Misc
bspc config split_ratio          0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Borders
bspc config border_width            2
# bspc config focused_border_color    "#4c83ad"
# bspc config normal_border_color     "#eceff0"
# bspc config presel_feedback_color   "#4c83ad"

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google Chrome desktop='^2'

# -------
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move
